CREATE DATABASE Hospital;
USE Hospital;
CREATE TABLE hospital_info1(personId int,hospital_name varchar(50),hospital_loc varchar(60),patientId int,patient_name varchar(60),patient_mobileNumber bigint,disease_name varchar(45),patient_addr varchar(50), patient_email varchar(60),doctor_name varchar(50));
DESC hospital_info1;
INSERT INTO hospital_info1 values(1,'Esha Clinic','Bangalore',100,'prerana','9353555400','Fever','bidar','preana@gmail.com','shreya');
INSERT INTO hospital_info1 values(2,'Manipal Hospitals','Bangalore',200,'Preeti',9663809145,'cold and cough','bidar','preeti@gmail.com','aruna');
INSERT INTO hospital_info1 values(3,'JSS Hospital','Mysore',300,'Sakshi',8618654684,'Body Pain','bidar','sakshii@gmail.com','aruna');
INSERT INTO hospital_info1 values(4,'KMC Hospital','Mangalore',400,'Rekksita',9448640680,'Typoid','bidar','rakshita@gmail.com','aruna');
INSERT INTO hospital_info1 values(5,'Apollo BGS Hospital','Mysore',500,'Prachi',8618649452,'Dengue','bidar','prachi@gmail.com','aruna');
INSERT INTO hospital_info1 values(6,'KIMS Hospital','Hubli',600,'Priyanka',8619257680,'Leg Pain','bidar','priyanak@gmail.com','aruna');
INSERT INTO hospital_info1 values(7,'Lakeview Hospital','Belagavi',700,'kavya',9449306474,'Malaria','bidar','pkvaya@gmail.com','aruna');
INSERT INTO hospital_info1 values(8,'Spandana Hospital','Hubli',800,'Sarika',9448618405,'Fever','bidar','sarika@gmail.com','aruna');
INSERT INTO hospital_info1 values(9,'Swayam Hospital','Belagavi',900,'Surekha',9494640680,'Cold','bidar','surekha@gmail.com','aruna');
INSERT INTO hospital_info1 values(10,'Fortis Hospital','Bangalore',1000,'nikita',869264680,'Body Pain','bidar','nikitai@gmail.com','aruna');
SELECT * FROM hospital_info1;


create database search;
use search;
CREATE TABLE tourist_places(palceId int,place_name varchar(50),place_loc varchar(50), OpeningHours varchar(50),Rating int,User_name varchar(50),User_loc varchar(50),UserId int,Entry_fees int,Guide_name varchar(50));
DESC tourist_places;
INSERT INTO tourist_places values(1,'zoo','Mysore','2hr',3,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'palce','Mysore','2hr',5,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'iskon','Mysore','2hr',5,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'lalbag','Mysore','2hr',5,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'kabanapark','Mysore','2hr',5,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'redport','Mysore','2hr',5,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'indiagate','Mysore','2hr',5,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'tajahotel','Mysore','2hr',5,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'adiyogi','Mysore','2hr',5,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'nandihills','Mysore','2hr',5,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'chikkbalapura','chikkabalapura','2hr',5,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'koti','koti','2hr',5,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'lingeshwar','Mysore','2hr',5,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'badami','banadami','2hr',5,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'batalakota','bagalkot','2hr',5,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'murudeshwar','Murudeshwar','2hr',5,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'gokarna','gokarna','2hr',5,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'hampi','hampe','2hr',5,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'Mysore','Mysore','2hr',5,'sarika','bengluru',200,50,'prerana');
INSERT INTO tourist_places values(1,'Bangalore','Bangalore','2hr',5,'sarika','bengluru',200,50,'prerana');
SELECT * FROM tourist_places;
